- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/camera/camera_info'
  gz_topic_name: '/cam1/camera/camera_info'
  ros_type_name: 'sensor_msgs/msg/CameraInfo'
  gz_type_name: 'ignition.msgs.CameraInfo'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/camera/image_raw'
  gz_topic_name: '/cam1/camera/image_raw'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/depth_camera/camera_info'
  gz_topic_name: '/cam1/depth_camera/camera_info'
  ros_type_name: 'sensor_msgs/msg/CameraInfo'
  gz_type_name: 'ignition.msgs.CameraInfo'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/depth_camera/depth_image'
  gz_topic_name: '/cam1/depth_camera/depth_image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/depth_camera/image'
  gz_topic_name: '/cam1/depth_camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/cam1/depth_camera/points'
  gz_topic_name: '/cam1/depth_camera/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name:  'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent1/imu'
  gz_topic_name: '/agent1/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent1/scan'
  gz_topic_name: '/agent1/lidar'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name: 'ignition.msgs.LaserScan'
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: best_effort
    durability: volatile

- ros_topic_name: '/agent1/scan/points'
  gz_topic_name: '/agent1/lidar/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent1/odom_gz'
  gz_topic_name: '/agent1/odom_gz'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'ignition.msgs.Odometry'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent2/imu'
  gz_topic_name: '/agent2/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent2/scan'
  gz_topic_name: '/agent2/lidar'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name: 'ignition.msgs.LaserScan'
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: best_effort
    durability: volatile

- ros_topic_name: '/agent2/scan/points'
  gz_topic_name: '/agent2/lidar/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent2/odom_gz'
  gz_topic_name: '/agent2/odom_gz'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'ignition.msgs.Odometry'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent3/imu'
  gz_topic_name: '/agent3/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent3/scan'
  gz_topic_name: '/agent3/lidar'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name: 'ignition.msgs.LaserScan'
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: best_effort
    durability: volatile

- ros_topic_name: '/agent3/scan/points'
  gz_topic_name: '/agent3/lidar/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS

- ros_topic_name: '/agent3/odom_gz'
  gz_topic_name: '/agent3/odom_gz'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'ignition.msgs.Odometry'
  direction: GZ_TO_ROS
